# Generated by Django 2.2.6 on 2019-10-16 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningform',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name=2),
            preserve_default=False,
        ),
    ]
