# Generated by Django 2.2.6 on 2019-10-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_auto_20191016_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningform',
            name='date',
            field=models.DateField(),
        ),
    ]
