# Generated by Django 2.2.6 on 2019-10-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("screening", "0003_auto_20191016_0540")]

    operations = [
        migrations.RemoveField(model_name="screeningform", name="date"),
        migrations.RemoveField(model_name="screeningform", name="time"),
    ]
