# Generated by Django 2.2.5 on 2019-10-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_auto_20191016_0543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScreeningForm',
            new_name='Screening',
        ),
    ]
